<?php


namespace frontend\models;

use Yii;
use yii\db\ActiveRecord;

class Country extends ActiveRecord
{


    public static function tableName()
    {
        return 'country';
    }



    public function fields()
    {
         $field=parent::fields();
        return $field;
    }

    public function extraFields()
    {
        $extraField= parent::extraFields(); // TODO: Change the autogenerated stub
        $extraField['extra_field1']=function(){
            return 'extra_value1';
        };
        return $extraField;
    }


}
