<?php

namespace frontend\modules\forum;

class Module extends \yii\base\Module
{


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->controllerNamespace='frontend\modules\forum\controllers';
        $this->layout='main';
    }






}
