<?php
namespace console\controllers;

use yii\console\Controller;
use yii\helpers\Console;

class HelloController extends Controller
{

    public $message='hello world';


    public function options($actionID)
    {
        $parents= parent::options($actionID); // TODO: Change the autogenerated stub
        $parents[]='message';

        return $parents;
    }

    public function optionAliases()
    {
        $parents= parent::optionAliases(); // TODO: Change the autogenerated stub
        $parents['m']='message';
        return $parents;

    }

    public function actionIndex($message1='asdf')
    {
        $this->stdout("格式如下：\r\n",Console::BG_GREEN);
        echo '这是选项：'.$this->message.'这是参数'.$message1;
        return 0;
    }


}

