<?php

namespace frontend\widgets;

use yii\base\Widget;

class HelloWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        ob_start();

    }


    public function run()
    {

        echo "this is a hello widget";
        $content=ob_get_clean();
        return $content;

    }

}
