<?php
namespace frontend\widgets;

use yii\base\Widget;

class ListWidget extends Widget
{


    public $lists;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (empty($this->lists)) {
            $this->lists = ['中国', '美国', '印度'];
        }
    }

    public function run()
    {
        return $this->render('lists', [
            'lists' => $this->lists
        ]);

    }


}
